<a href="https://colab.research.google.com/github/H-TAMURA-9250/EU_M_Math-Repository/blob/main/Chap5_1%2C5_2_Ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Chap05-1
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

# Set print options for precision to 3 decimal places
np.set_printoptions(precision=3)

sample_array = np.arange(10)
print('sample_array:',sample_array)

print(sample_array)

sample_array_slice = sample_array[0:5]
print(sample_array_slice)

sample_array_slice[0:3] = 10
print(sample_array_slice)

print(sample_array)

asmple_array_copy = np.copy(sample_array)
print(asmple_array_copy)

asmple_array_copy[0:3] = 20
print(asmple_array_copy)

print(sample_array)

sample_names = np.array(['a' , 'b' ,'c' , 'd ', 'a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)

sample_names == 'a'

data[sample_names == 'a']

sample_array_slice

sample_array: [0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]
[20 20 20  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]


In [ ]:
#Chap05_Ex-01
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

# Set print options for precision to 3 decimal places
np.set_printoptions(precision=3)

sample_names = np.array(['a' , 'b' ,'c' , 'd ', 'a'])
random.seed(0)
data = random.randn(5,5)

# Apply boolean indexing to filter rows of the 'data' array
data = data[sample_names == 'b']

print(sample_names)
print(data)

['a' 'b' 'c' 'd ' 'a']
[[-0.977  0.95  -0.151 -0.103  0.411]]


In [ ]:
#Chap05_Ex-02
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

# Set print options for precision to 3 decimal places
np.set_printoptions(precision=3)

sample_names = np.array(['a' , 'b' ,'c' , 'd ', 'a'])
random.seed(0)
data = random.randn(5,5)

# Apply boolean indexing to filter rows of the 'data' array for all samples except 'c'
data = data[sample_names != 'c']

print(sample_names)
print(data)

['a' 'b' 'c' 'd ' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [ ]:
#Chap05_Ex-02
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

# Set print options for precision to 3 decimal places
np.set_printoptions(precision=3)



In [ ]:
sample_data_array1 = np.arange(12).reshape(3,4)
sample_data_array2 = np.arange(12).reshape(3,4)

print('sample_data_array1:')
print(sample_data_array1)

print('\nsample_data_array2:')
print(sample_data_array2)

sample_data_array1:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

sample_data_array2:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 軸0 (行方向) に沿って配列を結合
combined_array_row = np.concatenate([sample_data_array1, sample_data_array2], axis=0)
print('結合された配列 (行方向):')
print(combined_array_row)

# 軸1 (列方向) に沿って配列を結合
combined_array_col = np.concatenate([sample_data_array1, sample_data_array2], axis=1)
print('\n結合された配列 (列方向):')
print(combined_array_col)

結合された配列 (行方向):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

結合された配列 (列方向):
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [ ]:
print(f"最大値 (Maximum): {np.max(sample_multi_array_data_2)}")
print(f"最小値 (Minimum): {np.min(sample_multi_array_data_2)}")
print(f"合計値 (Sum): {np.sum(sample_multi_array_data_2)}")
print(f"平均値 (Mean): {np.mean(sample_multi_array_data_2)}")

最大値 (Maximum): 15
最小値 (Minimum): 0
合計値 (Sum): 120
平均値 (Mean): 7.5


In [ ]:
#Chap05_Ex-02
sample_list = [1, 2, 3, 4, 5]
print(f"元のリスト: {sample_list}")

# リストをNumPy配列に変換
sample_array = np.array(sample_list)

# ブロードキャスト機能を使って各要素に3を加える
result_array = sample_array + 3

print(f"3を加えたNumPy配列: {result_array}")

# 必要であれば、再度リストに変換することも可能です
result_list = result_array.tolist()
print(f"3を加えたリスト: {result_list}")

元のリスト: [1, 2, 3, 4, 5]
3を加えたNumPy配列: [4 5 6 7 8]
3を加えたリスト: [4, 5, 6, 7, 8]
